namespace StatCan.Chms.Client;

/// <summary>
/// This is the client for the CHMS Open API.
///
/// The actual implementation was generated by the Microsoft.dotnet-openapi tool and can be found
/// at ./obj/ChmsOpenApiClient.cs
///
/// See https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-6.0.
/// </summary>
public partial class ChmsOpenApiClient
{
    
}